---
# Playbook to install k8s without a CNI using KubeSpray
  - name: Install k8s cluster without CNI
    hosts: centraljumphost
    gather_facts: yes
    tasks:
      # Copy inventory Yaml file from BMS cloned folder into jumphost
      - name: Copy inventory into jumphost
        ansible.builtin.copy:
          src: k8s_inventory.yaml
          dest: kubespray/inventory/inventory.yaml
      
      # Update inventory file using /etc/hosts
      - name: Update the inventory file
        replace:
          path: kubespray/inventory/inventory.yaml
          regexp: >-
            ansible_host: centralctrl
          replace: >-
            ansible_host: {{ hostvars['centralctrl'].ansible_host }}
      - name: Update the inventory file
        replace:
          path: kubespray/inventory/inventory.yaml
          regexp: >-
            ansible_host: centralworker1
          replace: >-
            ansible_host: {{ hostvars['centralworker1'].ansible_host }}

      - name: Update the inventory file
        replace:
          path: kubespray/inventory/inventory.yaml
          regexp: >-
            ansible_host: centralworker2
          replace: >-
            ansible_host: {{ hostvars['centralworker2'].ansible_host }}
 
      # Test that the cluster nodes are reachable
      - name: Ping Test  
        command: "ansible -i /root/kubespray/inventory/inventory.yaml -m ping all"
        register: output_ping

      # Deploy the cluster
      - name: Deploy Cluster - This might take some time ...
        command: "ansible-playbook -i /root/kubespray/inventory/inventory.yaml /root/kubespray/cluster.yml"
        register: output_deploy

      # Create the .kube directory on the Kubespray/jumphost 
      - name : Create Directory
        ansible.builtin.file:
          path: ~/.kube
          state: directory
          mode: '0755'
    
      # Copy the k8s config to .kube directory for managing the k8s cluster using kubect;
      - name: Copying kube config into .kube directory for managing the cluster
        ansible.builtin.copy:
          src: /tmp/mycluster/admin.conf
          dest: ~/.kube/config
          remote_src: yes
